language: python

python:
    - '3.6'

cache:
    ccache: true
    pip: true

before_install:
  - sudo apt-get install gfortran
  - pip install coveralls
  - pip install python-coveralls
  - pip install h5py

install:
  - git clone https://github.com/sibirrer/fastell4py.git
  - cd fastell4py
  - cd ..
  - git clone https://github.com/jiwoncpark/baobab.git
  - cd baobab
  - pip install -e . -r requirements.txt
  - cd ..
  - pip install .

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3

script:
  - coverage run --source ovejero setup.py test

after_success:
  - codecov
  - coveralls